name: 'Automathic Package Version Bump'
description:
  'Automatically bump the package version following semantic versioning based on
  the type from the PR title'
author: 'David Velásquez'

runs:
  using: node20
  main: dist/index.js
